// All 56 emotions from migrations/2.sql
export const EMOTIONS_DATA = [
  // Basic emotions (Ekman's 6)
  { id: 1, name: 'Joy', category: 'positive', color: '#10b981' },
  { id: 2, name: 'Happiness', category: 'positive', color: '#22c55e' },
  { id: 3, name: 'Excitement', category: 'positive', color: '#f59e0b' },
  { id: 4, name: 'Contentment', category: 'positive', color: '#84cc16' },
  { id: 5, name: 'Gratitude', category: 'positive', color: '#06b6d4' },
  { id: 6, name: 'Love', category: 'positive', color: '#ec4899' },
  { id: 7, name: 'Pride', category: 'positive', color: '#8b5cf6' },
  { id: 8, name: 'Hope', category: 'positive', color: '#3b82f6' },
  { id: 9, name: 'Compassion', category: 'positive', color: '#14b8a6' },
  { id: 10, name: 'Amusement', category: 'positive', color: '#f97316' },

  // Negative emotions
  { id: 11, name: 'Sadness', category: 'negative', color: '#6b7280' },
  { id: 12, name: 'Anger', category: 'negative', color: '#ef4444' },
  { id: 13, name: 'Fear', category: 'negative', color: '#7c3aed' },
  { id: 14, name: 'Anxiety', category: 'negative', color: '#f59e0b' },
  { id: 15, name: 'Worry', category: 'negative', color: '#eab308' },
  { id: 16, name: 'Frustration', category: 'negative', color: '#dc2626' },
  { id: 17, name: 'Irritation', category: 'negative', color: '#ea580c' },
  { id: 18, name: 'Guilt', category: 'negative', color: '#7c2d12' },
  { id: 19, name: 'Shame', category: 'negative', color: '#991b1b' },
  { id: 20, name: 'Embarrassment', category: 'negative', color: '#be185d' },
  { id: 21, name: 'Loneliness', category: 'negative', color: '#374151' },
  { id: 22, name: 'Jealousy', category: 'negative', color: '#059669' },
  { id: 23, name: 'Envy', category: 'negative', color: '#16a34a' },
  { id: 24, name: 'Disappointment', category: 'negative', color: '#9333ea' },
  { id: 25, name: 'Grief', category: 'negative', color: '#1f2937' },
  { id: 26, name: 'Despair', category: 'negative', color: '#111827' },
  { id: 27, name: 'Disgust', category: 'negative', color: '#65a30d' },
  { id: 28, name: 'Contempt', category: 'negative', color: '#a16207' },

  // Neutral/Mixed emotions
  { id: 29, name: 'Surprise', category: 'neutral', color: '#0ea5e9' },
  { id: 30, name: 'Confusion', category: 'neutral', color: '#6366f1' },
  { id: 31, name: 'Curiosity', category: 'neutral', color: '#8b5cf6' },
  { id: 32, name: 'Boredom', category: 'neutral', color: '#71717a' },
  { id: 33, name: 'Indifference', category: 'neutral', color: '#9ca3af' },
  { id: 34, name: 'Nostalgia', category: 'neutral', color: '#a855f7' },
  { id: 35, name: 'Anticipation', category: 'neutral', color: '#06b6d4' },
  { id: 36, name: 'Relief', category: 'neutral', color: '#10b981' },
  { id: 37, name: 'Acceptance', category: 'neutral', color: '#6b7280' },
  { id: 38, name: 'Calmness', category: 'neutral', color: '#0891b2' },

  // Complex emotions
  { id: 39, name: 'Overwhelmed', category: 'negative', color: '#dc2626' },
  { id: 40, name: 'Stressed', category: 'negative', color: '#ea580c' },
  { id: 41, name: 'Confident', category: 'positive', color: '#3b82f6' },
  { id: 42, name: 'Insecure', category: 'negative', color: '#7c3aed' },
  { id: 43, name: 'Motivated', category: 'positive', color: '#f59e0b' },
  { id: 44, name: 'Apathy', category: 'neutral', color: '#6b7280' },
  { id: 45, name: 'Optimism', category: 'positive', color: '#eab308' },
  { id: 46, name: 'Pessimism', category: 'negative', color: '#991b1b' },
  { id: 47, name: 'Vulnerable', category: 'negative', color: '#be185d' },
  { id: 48, name: 'Empowered', category: 'positive', color: '#7c3aed' },
  { id: 49, name: 'Betrayed', category: 'negative', color: '#dc2626' },
  { id: 50, name: 'Appreciated', category: 'positive', color: '#10b981' },
  { id: 51, name: 'Neglected', category: 'negative', color: '#6b7280' },
  { id: 52, name: 'Inspired', category: 'positive', color: '#8b5cf6' },
  { id: 53, name: 'Defeated', category: 'negative', color: '#374151' },
  { id: 54, name: 'Energized', category: 'positive', color: '#f97316' },
  { id: 55, name: 'Drained', category: 'negative', color: '#71717a' },
  { id: 56, name: 'Peaceful', category: 'positive', color: '#06b6d4' },
  { id: 57, name: 'Restless', category: 'negative', color: '#eab308' },
  { id: 58, name: 'Fulfilled', category: 'positive', color: '#22c55e' },
];